/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WealthImport } from './routes/wealth'
import { Route as ProfileImport } from './routes/profile'
import { Route as InvestmentsImport } from './routes/investments'
import { Route as IncomeImport } from './routes/income'
import { Route as ExpensesImport } from './routes/expenses'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WealthRoute = WealthImport.update({
  path: '/wealth',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const InvestmentsRoute = InvestmentsImport.update({
  path: '/investments',
  getParentRoute: () => rootRoute,
} as any)

const IncomeRoute = IncomeImport.update({
  path: '/income',
  getParentRoute: () => rootRoute,
} as any)

const ExpensesRoute = ExpensesImport.update({
  path: '/expenses',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/expenses': {
      preLoaderRoute: typeof ExpensesImport
      parentRoute: typeof rootRoute
    }
    '/income': {
      preLoaderRoute: typeof IncomeImport
      parentRoute: typeof rootRoute
    }
    '/investments': {
      preLoaderRoute: typeof InvestmentsImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/wealth': {
      preLoaderRoute: typeof WealthImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ExpensesRoute,
  IncomeRoute,
  InvestmentsRoute,
  ProfileRoute,
  WealthRoute,
])

/* prettier-ignore-end */
